"""Dia2 (Nari Labs, 2B) TTS provider: dialogue-native, two speakers, English.

Chosen over Dia 1 after a listening test on 2026-09-23 (Dia 1: 110 words/min,
voices too similar; Dia2: 152 words/min). The renderer keeps the two voices
stable across chunks by conditioning later chunks on clips from the first.
"""

from __future__ import annotations

from pathlib import Path

from ..config import VOZONDA_ROOT
from ..env import env
from ..plugins.types import Permission, PluginKind, PluginMeta

RENDER_PY = Path(
    env("DIA2_PY",
        str(VOZONDA_ROOT / "projects/tts-spike/.venv-dia2/bin/python"),
    ),
)

VOICES_DIR = Path(
    env("DIA2_VOICES",
        str(VOZONDA_ROOT / "projects/tts-spike/voices/dia2"),
    ),
)

# Curated voices: clips generated by Dia2 itself (no human voice), each with its
# transcript; the renderer conditions every chunk on them. The clip doubles as
# the voice's listening sample.
SPEAKERS = [
    {"id": "host_m", "label": "Host (m), clear", "gender": "m", "native": "English"},
    {"id": "host_f", "label": "Host (f), warm", "gender": "f", "native": "English"},
    {"id": "deep_m", "label": "Deep (m)", "gender": "m", "native": "English"},
    {"id": "calm_m", "label": "Calm (m)", "gender": "m", "native": "English"},
    {"id": "bright_f", "label": "Bright (f)", "gender": "f", "native": "English"},
    {"id": "lively_f", "label": "Lively (f)", "gender": "f", "native": "English"},
]


def sample_path(voice_id: str) -> Path | None:
    """The voice's reference clip, which is also its listening sample."""
    if voice_id not in {s["id"] for s in SPEAKERS}:
        return None
    p = VOICES_DIR / f"{voice_id}.wav"
    return p if p.is_file() else None


def is_installed() -> bool:
    return RENDER_PY.exists()


META = PluginMeta(
    id="dia2",
    kind=PluginKind.TTS_ENGINE,
    label="dia2 (Nari Labs 2B, dialogue-native 2 speakers, English)",
    permissions=frozenset({Permission.SUBPROCESS, Permission.GPU}),
    renderer="render_dia2.py",
    license="Apache-2.0",
    commercial_use=True,
    supports_paralinguistic_tags=False,
    ui_badge="local GPU",
    ui_fix_hint=(
        "create a venv with torch for your GPU plus `pip install -e` of "
        "github.com/nari-labs/dia2 and set VOZONDA_DIA2_PY"
    ),
)
