"""Dia2 renderer: same CLI contract as render_kokoro.py.

--config cfg.json with {segments, voices, gap_ms, language, out}; writes the
WAV to cfg["out"] plus a .timing.json sidecar with per-turn durations.

Dia2 (Nari Labs, Apache-2.0) speaks a whole [S1]/[S2] dialogue in one pass,
up to ~2 minutes of context. Longer episodes are rendered in chunks. Without
a reference Dia2 picks new voices on every pass (often two similar ones), so
every chunk is conditioned on a curated reference clip per speaker
(voices/dia2/<id>.wav, generated by Dia2 itself, with its transcript in
<id>.json). Without curated clips, chunk 1 renders free and one clip per
speaker is cut from it for the later chunks. Prefix transcripts are known
text, so Whisper (which Dia2 would load per prefix, twice per pass) never runs.

Runs as a plain file under the Dia2 venv: stdlib and the engine only, no
vozonda_api imports. Pure helpers are tested without torch.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


def _env(name: str, default: str | None = None) -> str | None:
    """vozonda_api.env without a top-level import: plain-file runs lack the path."""
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from vozonda_api.env import env as _read_env

    return _read_env(name, default)

MODEL = "nari-labs/Dia2-2B"
# Words per chunk: ~150 wpm keeps a chunk near 70 s, leaving room for the two
# prefix clips inside the ~2 minute context.
CHUNK_WORDS = 170
# Reference clip per speaker, cut from chunk 1.
REF_MIN_S = 3.0
REF_MAX_S = 10.0
# Curated voices (voices/dia2/<id>.wav + .json) used when a speaker has none chosen.
DEFAULT_VOICES = {"[S1]": "host_m", "[S2]": "host_f"}


def language_ok(language: str) -> bool:
    """Dia2 is English only; the pipeline passes display names ("English")."""
    return str(language or "en").strip().lower() in {"en", "english"}


def clean_text(text: str) -> str:
    """Drop stage directions and characters Dia2's parser treats specially."""
    text = re.sub(r"\[[^\]]*\]", "", text)
    text = re.sub(r"\([^)]*\)", "", text)
    text = text.replace("’", "'").replace(":", " ")
    return " ".join(text.split())


def speaker_tags(segments: list[dict]) -> dict[str, str]:
    """First speaker -> [S1], second -> [S2]; Dia2 has exactly two voices."""
    order: list[str] = []
    for seg in segments:
        spk = str(seg.get("speaker", "A"))
        if spk not in order:
            order.append(spk)
    if len(order) > 2:
        raise ValueError(f"Dia2 supports at most 2 speakers, got {len(order)}: {order}")
    return {spk: f"[S{i + 1}]" for i, spk in enumerate(order)}


def build_turns(segments: list[dict]) -> list[dict]:
    """[{seg, tag, text, words}] for every segment; empty text keeps its slot."""
    tags = speaker_tags(segments)
    turns = []
    for i, seg in enumerate(segments):
        text = clean_text(str(seg.get("text", "")))
        turns.append({"seg": i, "tag": tags[str(seg.get("speaker", "A"))], "text": text,
                      "words": text.split()})
    return turns


def chunk_turns(turns: list[dict], max_words: int = CHUNK_WORDS) -> list[list[dict]]:
    """Group spoken turns into chunks of at most max_words; a turn is never split."""
    chunks: list[list[dict]] = []
    current: list[dict] = []
    count = 0
    for t in turns:
        if not t["words"]:
            continue
        if current and count + len(t["words"]) > max_words:
            chunks.append(current)
            current, count = [], 0
        current.append(t)
        count += len(t["words"])
    if current:
        chunks.append(current)
    return chunks


def chunk_script(chunk: list[dict]) -> str:
    return " ".join(f"{t['tag']} {t['text']}" for t in chunk)


def word_speakers(chunk: list[dict]) -> list[tuple[str, str, int]]:
    """(word, tag, turn index in chunk) in the order Dia2 reports timestamps."""
    return [(w, t["tag"], i) for i, t in enumerate(chunk) for w in t["words"]]


def turn_starts(chunk: list[dict], timestamps: list[tuple[str, float]]) -> list[float] | None:
    """Start time of every turn in the chunk, or None if the timestamps do not
    line up with the script words (then callers fall back to text length)."""
    stamps = [(w, s) for w, s in timestamps if w]
    spoken = word_speakers(chunk)
    if len(stamps) != len(spoken):
        return None
    starts: list[float] = []
    last = -1
    for (_, sec), (_, _, turn) in zip(stamps, spoken):
        if turn != last:
            starts.append(float(sec))
            last = turn
    return starts


def turn_durations(chunk: list[dict], starts: list[float] | None, total_s: float) -> list[float]:
    """Per-turn durations inside one chunk (exact with timestamps, else by length)."""
    if starts and len(starts) == len(chunk):
        bounds = [*starts[1:], total_s]
        return [round(max(0.0, b - a), 3) for a, b in zip(starts, bounds)]
    chars = [max(1, len(t["text"])) for t in chunk]
    return [round(total_s * c / sum(chars), 3) for c in chars]


def reference_spans(chunk: list[dict], timestamps: list[tuple[str, float]], total_s: float,
                    ) -> dict[str, tuple[float, float, list[tuple[str, float]]]]:
    """Per speaker tag: (start, end, [(word, seconds from clip start)]) of the
    longest turn, capped at REF_MAX_S; speakers under REF_MIN_S are skipped."""
    starts = turn_starts(chunk, timestamps)
    if not starts or len(starts) != len(chunk):
        return {}
    stamps = [(w, s) for w, s in timestamps if w]
    spoken = word_speakers(chunk)
    ends = [*starts[1:], total_s]
    best: dict[str, tuple[float, float, list[tuple[str, float]]]] = {}
    for i, t in enumerate(chunk):
        a, b = starts[i], min(ends[i], starts[i] + REF_MAX_S)
        words = [(w, round(s - a, 3)) for (w, s), (_, _, turn) in zip(stamps, spoken)
                 if turn == i and s < b]
        if b - a < REF_MIN_S or not words:
            continue
        prev = best.get(t["tag"])
        if prev is None or (b - a) > (prev[1] - prev[0]):
            best[t["tag"]] = (a, b, words)
    return best


def voices_dir() -> Path:
    """Curated reference voices; mirrors providers/dia2.py VOICES_DIR (tests keep them in sync)."""
    explicit = _env("DIA2_VOICES")
    if explicit:
        return Path(explicit)
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
    from vozonda_api.config import VOZONDA_ROOT

    return Path(VOZONDA_ROOT) / "projects/tts-spike/voices/dia2"


def curated_reference(vdir: Path, voice_id: str) -> tuple[str, list[tuple[str, float]]] | None:
    """(<id>.wav, words) for a curated voice, or None. Ids are plain names only."""
    if not re.fullmatch(r"[a-z0-9_]+", voice_id or ""):
        return None
    wav, meta = vdir / f"{voice_id}.wav", vdir / f"{voice_id}.json"
    if not (wav.is_file() and meta.is_file()):
        return None
    words = [(str(w), float(t)) for w, t in json.loads(meta.read_text())["words"]]
    return (str(wav), words) if words else None


def timbre_for(voices: dict, speaker: str) -> str:
    vc = voices.get(speaker, {})
    return str((vc.get("timbre") if isinstance(vc, dict) else vc) or "")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    args = ap.parse_args()

    cfg = json.loads(Path(args.config).read_text())
    segments = cfg["segments"]
    gap_ms = int(cfg.get("gap_ms", 250))
    out = Path(cfg["out"])
    out.parent.mkdir(parents=True, exist_ok=True)

    if not language_ok(cfg.get("language", "en")):
        print(f"Dia2 supports English only, got {cfg.get('language')!r}", file=sys.stderr)
        sys.exit(1)
    try:
        turns = build_turns(segments)
    except ValueError as exc:
        print(f"Dia2 dialogue error: {exc}", file=sys.stderr)
        sys.exit(1)
    chunks = chunk_turns(turns)
    if not chunks:
        print("no audio produced", file=sys.stderr)
        sys.exit(1)

    import numpy as np
    import soundfile as sf
    import torch
    from dia2 import Dia2, GenerationConfig, SamplingConfig
    from dia2.runtime import voice_clone

    torch.manual_seed(int(cfg.get("seed", 1234)))
    dia = Dia2.from_repo(MODEL, device="cuda", dtype="bfloat16")
    gen_cfg = GenerationConfig(cfg_scale=float(cfg.get("cfg_scale", 4.0)),
                               audio=SamplingConfig(temperature=float(cfg.get("audio_temperature", 0.6)), top_k=50),
                               use_cuda_graph=True)
    sr = dia.sample_rate

    # Prefix transcripts come from the script, not from Whisper.
    known_words: dict[str, list[tuple[str, float]]] = {}

    def transcribe_known(path, device, language=None):
        words = known_words[str(path)]
        return [voice_clone.WhisperWord(text=w, start=s,
                                        end=(words[i + 1][1] if i + 1 < len(words) else s + 0.3))
                for i, (w, s) in enumerate(words)]

    voice_clone.transcribe_words = transcribe_known

    work = out.parent / f".{out.stem}_dia2"
    work.mkdir(parents=True, exist_ok=True)
    refs: dict[str, str] = {}
    # Curated voices condition every chunk from the start; without them the
    # voices are cut from chunk 1 (below).
    vdir = voices_dir()
    tags = speaker_tags(segments)
    curated = {tag: curated_reference(vdir, timbre_for(cfg.get("voices", {}), spk))
               or curated_reference(vdir, DEFAULT_VOICES[tag]) for spk, tag in tags.items()}
    if all(curated.values()):
        for tag, (path, words) in curated.items():
            refs[tag] = path
            known_words[path] = words
    pieces: list = []
    durations: dict[int, float] = {}
    gap = np.zeros(int(sr * gap_ms / 1000), dtype=np.float32)

    for n, chunk in enumerate(chunks):
        prefix = {}
        if "[S1]" in refs:
            prefix["prefix_speaker_1"] = refs["[S1]"]
            if "[S2]" in refs:
                prefix["prefix_speaker_2"] = refs["[S2]"]
        res = dia.generate(chunk_script(chunk), config=gen_cfg, **prefix)
        wav = res.waveform.detach().float().cpu().numpy().reshape(-1)
        total_s = len(wav) / sr
        starts = turn_starts(chunk, res.timestamps)
        for t, d in zip(chunk, turn_durations(chunk, starts, total_s)):
            durations[t["seg"]] = d
        durations[chunk[-1]["seg"]] = round(durations[chunk[-1]["seg"]] + len(gap) / sr, 3)
        if n == 0 and not refs:
            for tag, (a, b, words) in reference_spans(chunk, res.timestamps, total_s).items():
                ref = work / f"ref_{tag.strip('[]').lower()}.wav"
                sf.write(ref, wav[int(a * sr):int(b * sr)], sr)
                refs[tag] = str(ref)
                known_words[str(ref)] = words
        pieces.extend([wav, gap])
        print(f"  chunk {n + 1}/{len(chunks)} ok ({total_s:.1f}s, prefix={'yes' if prefix else 'no'})",
              flush=True)

    full = np.concatenate(pieces)
    sf.write(out, full, sr)
    timing = [durations.get(i, 0.0) for i in range(len(segments))]
    (out.parent / f"{out.stem}.timing.json").write_text(json.dumps(timing))
    print(f"dia2: {len(chunks)} chunks, {len(full) / sr:.1f}s total, written to {out}")


if __name__ == "__main__":
    main()
